package routers

import (
	"swagger/controllers"

	"github.com/gin-gonic/gin"

	_ "swagger/docs" // docs is generated by Swag CLI, you have to import it.

	ginSwagger "github.com/swaggo/gin-swagger"

	swaggerfiles "github.com/swaggo/files"
)

// @title Car API
// @version 1.0
// @description This is a sample service for managing cars
// @termsOfService http://swagger.io/terms/
// @contact.name API Support
// @contact.email soberkoder@swagger.io
// @licence.name Apache 2.0
// @licence.url http://www.apache.org/lisenses/LICENSE-2.0.html
// @host localhost:8080
// @BasePath /
func StartServer() *gin.Engine {
	router := gin.Default()

	// Read
	router.GET("/cars/:id", controllers.GetOneCars)
	// Create
	router.POST("/cars", controllers.CreateCars)
	// Real All
	router.GET("/cars", controllers.GetAllCars)
	// Update
	router.PATCH("/cars/:id", controllers.UpdateCars)
	// DELETE
	router.DELETE("/cars/:id", controllers.DeleteCars)

	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerfiles.Handler))

	return router
}
